### ISSUE TITLE
Bullet not well displayed

### ISSUE THREAD

**Issue by T4m** [dasistwas/moodle-block_simple_nav#5]
Hello @dasistwas ,
Thank you very much for your plugin. It's the only one I could find that allow to list filtered courses, regardless enrolments.

Do you still maintain it ?

I have an issue with Moodle 3.5.8, the bullets are not very well displayed :
![simple-nav-issue](https://user-images.githubusercontent.com/2522416/68138320-a72c8c00-ff28-11e9-8961-db87dfaab317.png)

* Bullet covering the first level element
* Bullet rotate to an "open state" even when the node is empty

Is it a compatibility issue with my theme (Boost) ?
Did I miss something ?

Thank you

**Comment by dasistwas** [comment]
Hi, this is not optimised for BOOST (BS4). I stopped working on that plugin as the institution, that ordered that plugin does not use it anymore. So there is no funding available for any further development.
